theme: jekyll-theme-cayman
title: "COVID-19: The Great Reset" – Resumo e crítica (e-book e audiobook por Gustavo Moraes)
description: Você saberá porque conhecer “The Great Reset”, do Fórum Econômico Mundial, é mais importante do que você imagina.